# Generated by Django 3.0 on 2019-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlashcardsWeb', '0003_deck_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='card',
            name='usageExample',
            field=models.CharField(max_length=64),
        ),
    ]
